theme: minima
minima:
  skin: classic
  header_pages:
  - index.md
  custom_css:
    - /assets/css/custom.css
  include:
    - custom-head.html

sass:
  style: compressed

defaults:
  - scope:
      path: "products"
    values:
      nav_exclude: true
